configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/meorphis-test%2Fmeorphis-test-40-e1061ff215dc37c9e4009e165fbf512a80e6f21cba211ff70027d8fb9a6e242f.yml
