name: Fake Workflow
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.event.action }}
      - run: echo ${{ github.event.pull_request.merged }}
      - run: echo ${{ github.event.pull_request.head.ref }}